//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clothes_Shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        public string MASP { get; set; }
        public string TENSP { get; set; }
        public string ANHSP { get; set; }
        public string SIZE { get; set; }
        public string THUONGHIEU { get; set; }
        public string CHATLIEU { get; set; }
        public string MOTA { get; set; }
        public Nullable<bool> SPKM { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public Nullable<double> GIABD { get; set; }
        public Nullable<double> GIAHT { get; set; }
        public Nullable<System.DateTime> NGAYDANG { get; set; }
        public Nullable<int> MALSP { get; set; }
    }
}
